### ISSUE TITLE
No message from equipment

### ISSUE THREAD

**Issue by Ikabodo** [jessev14/dnd5e-character-monitor#21]
I'm not getting a message when equipping/unequipping equippment.

![image](https://user-images.githubusercontent.com/7766890/189872002-674e5ab2-593a-43b4-9d2d-67522cd0ae3f.png)

There is an error in the log like this:
```js
dnd5e-character-monitor.js:335 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'OWNER')
[Detected 2 packages: dnd5e-character-monitor, advanced-macros]
    at dnd5e-character-monitor.js:335:99
    at Users.filter (commons.js:2787:14)
    at Object.fn (dnd5e-character-monitor.js:335:28)
    at #call (foundry.js:688:20)
    at Hooks.call (foundry.js:670:38)
    at ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:12651:47)
    at async ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:12564:22)
    at async Item5e.updateDocuments (commons.js:5674:23)
    at async eval (eval at <anonymous> (Macros.js:61:16), <anonymous>:274:1)
    ```

**Comment by jessev14** [comment]
This module has not been update for Foundry V10.
